---
title: "Patches"
author: "ZR"
date: "8/18/2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

`

## Libraries
```{r}
library(readr)
library(readxl)
library(ggplot2)
library(hrbrthemes)
library(ggbump)
library(tidyverse)
```


## Add Data

```{r}
AGBM <- read_csv("Data/AGBM.csv")
BGBM <- read_excel("Data/BGBM.xlsx")
AG_Pct <- read_excel("Data/AG_Pct.xlsx")
Soil <- read_excel("Data/Soil.xlsx")
BGBM_Aggregated <- read_excel("Data/BGBM.xlsx", sheet = "BGBM_Aggregated")
View(Soil)
View(AG_Pct)
View(BGBM)
View(AGBM)
View(BGBM_Aggregated)
```

## Organize data
### AG biomass and cover
### BGBM
### Soil C
```{r}

```


## Plots

```{r}
# AGBM
ggplot(AGBM, aes(x=`SECTION`, y=`CarbonAGBM(kgC/m2)`, color=SITE_ID)) + 
    geom_violin() +
  facet_grid(SITE_ID ~ PATCH, scales = "fixed")+
    theme_classic()

ggplot(AGBM, aes(x=`Area_m2`, y=`Perimeter_m`, color=SITE_ID)) + 
    geom_point() +
    theme_classic()

ggplot(AGBM, aes(x=`Area_m2`, y=`CarbonAGBM(kgC/m2)`, color=SITE_ID)) + 
    geom_point() +
    theme_classic()

ggplot(AGBM, aes(x=`ShapeRatio`, y=`CarbonAGBM(kgC/m2)`, color=SITE_ID)) + 
    geom_point() +
    theme_classic()

ggplot(AGBM, aes(x=`Perimeter_m`, y=`CarbonAGBM(kgC/m2)`, color=SITE_ID)) + 
    geom_point() +
    theme_classic()
```

```{r}
#BGBM

ggplot(BGBM_Aggregated, aes(x=`ShapeRatio`, y=`Biomass/core_g/m2`, color=Site)) + 
    geom_point() +
  geom_smooth()+
  facet_grid(SampleType ~ Patch, scales = "free")+
    theme_classic()

ggplot(BGBM_Aggregated, aes(x=`Area_m2`, y=`Biomass/core_g/m2`, color=SampleType)) + 
    geom_point() +
  geom_smooth()+
    theme_classic()

ggplot(BGBM_Aggregated, aes(x=`ShapeRatio`, y=`Biomass/core_g/m2`, color=SampleType)) + 
    geom_point() +
  geom_smooth()+
  facet_grid(Site ~ Patch, scales = "fixed")+
    theme_classic()

ggplot(BGBM_Aggregated, aes(x=`ShapeRatio`, y=`Biomass/core_g/m2`, color=SampleType)) + 
    geom_point() +
  geom_smooth()+
  facet_grid(Site ~ Patch, scales = "free")+
    theme_classic()

```

```{r}
## Boxplot area/shape ?
ggplot(BGBM_Aggregated, aes(x=`ShapeRatio`, y=`Biomass/core_g/m2`, color=SampleType)) + 
    geom_boxplot()+
  facet_grid(Site ~ Patch, scales = "free")+
    theme_classic()
ggplot(BGBM_Aggregated, aes(x=`ShapeRatio`, y=`Biomass/core_g/m2`, color=SampleType)) + 
    geom_boxplot()+
  facet_grid(Site ~ Section, scales = "free")+
    theme_classic()
##
```
```{r}
## Live roots only graphs
LiveBGBM <- filter(BGBM_Aggregated, SampleType == "AliveRoots")

ggplot(LiveBGBM, aes(x=`ShapeRatio`, y=`Biomass/core_g/m2`, color=Site)) + 
    geom_point() +
  geom_smooth()+
  facet_grid(Site ~ Patch, scales = "free")+
    theme_classic()

ggplot(LiveBGBM, aes(x=`ShapeRatio`, y=`Biomass/core_g/m2`, color=Site)) + 
    geom_point() +
  geom_smooth()+
#  facet_grid(Site ~ Patch, scales = "free")+
    theme_classic()

ggplot(LiveBGBM, aes(x=`Area_m2`, y=`Biomass/core_g/m2`, color=Site)) + 
    geom_point() +
  geom_smooth()+
#  facet_grid(Site ~ Patch, scales = "free")+
    theme_classic()

```

